### ISSUE TITLE
Update DeFillama adapter to include: Smart Vaults + Lock Vaults + veVCX

### ISSUE THREAD

**Issue by Mischa0x** [Popcorn-Limited/vaultcraft#182]
Considering there is 500K in FRAX and 519K in the Balancer pool, those are not insignificant figures. They should be be included in TVL

**Comment by Mischa0x** [comment]
not fixed

**Comment by alec-pop** [comment]
Updated DeFillama adapter to include:
Smart Vaults + Lock Vaults + veVCX

Then use the DeFillama TVL on the FE to ensure consistent values
