### ISSUE TITLE
Stats DB needs to be updated to display all variables

### ISSUE THREAD

**Issue by Mischa0x** [Popcorn-Limited/vaultcraft#183]
- Burned VCX
- oVCX emissions
- oVCX exercised
- Total Revenue
- Smart Vault Fees
- oVCX Revenue
- TVL chart should include Balancer LP + Frax + Smart Vaults

<img width="809" alt="Screenshot 2024-01-01 at 2 12 20 PM" src="https://github.com/Popcorn-Limited/vaultcraft/assets/88731911/b544515c-577c-4e21-844e-b8dece32b6fe">

**Comment by alec-pop** [comment]
Other fields to add:
Percent of VCX LP Locked
Average lock time for veVCX
