### ISSUE TITLE
Increase veVCX lock amount error

### ISSUE THREAD

**Issue by J-n-a-k** [Popcorn-Limited/vaultcraft#194]
Increasing the lock amount by the maximum VCX-LP in your wallet returns the error _The contract function "increase_amount" reverted with the following reason: BAL#407"_

I was able to get it to work by deleting the last few decimal places in the "amount VCX" field. 

Joey N (discord: joey_pop)

**Comment by alec-pop** [comment]
Closed with 10k oVCX reward
