### ISSUE TITLE
Changing gauge weight vote does not work

### ISSUE THREAD

**Issue by J-n-a-k** [Popcorn-Limited/vaultcraft#195]
After the 10 day voting period expires, changing your vote does not work. 

I originally voted for one vault with 100% of my voting power. 10 days later when I was prompted to cast votes again, I was not able to vote for another vault. I received this error:

_The contract function "vote_for_many_gauge_weights" reverted with the following reason:
Used too much power_

The only action that didn't produce that error was voting for the vault I had previously voted for with some percentage of my voting power. I thought maybe I would have to reduce my vote for that vault first in order free up any remaining voting power for use on another vault. But that didn't work, either. Once I reduced my vote, I was no longer able to take any voting action and was stuck with only part of my voting power in use. Refreshing the page didn't make a difference.
___________

Update: I returned to the vault page an hour later and was able to use my remaining voting power on a different vault. But I had to manually make sure I didn't try to use more voting power than I had left instead of the UI automatically stopping me from going over. So still not great.

Joey N (Discord: joey_pop)

**Comment by alec-pop** [comment]
Closed with 10k oVCX reward.

Improvements to the UI have been made by setting sliders to existing vote weights instead of starting from 0
