### ISSUE TITLE
Rewards APRs are inaccurate for FraxLend GMX and WBTC vaults

### ISSUE THREAD

**Issue by J-n-a-k** [Popcorn-Limited/vaultcraft#207]
At least I'm assuming they're inaccurate. If not, please let me know and I'll yeet my life savings into them...

Min/Max APRs barely changed as TVL went from $100 to over $25K in each of these vaults. This week's ARB rewards were 945 ARB for each afaik. So unless FXS rewards are going to be insane, something is off.

joey_pop

<img width="1605" alt="Screenshot 2024-01-22 at 12 38 51 PM" src="https://github.com/Popcorn-Limited/vaultcraft/assets/155658337/2c451512-cc86-4356-b50f-8c20b6e3bc5b">

**Comment by alec-pop** [comment]
Rewards are correct when checking annualized ARB / TVL at the block of the last AID distribution.

Will address improvement in more recent ticket

**Comment by alec-pop** [comment]
Closed with 1k oVCX reward
