### ISSUE TITLE
Unable to add additional FRAX to existing deposit in GMX Lock Vault

### ISSUE THREAD

**Issue by J-n-a-k** [Popcorn-Limited/vaultcraft#208]
I deposited FRAX in this vault last week with no issue. When I tried to add more yesterday and again today, I wasn't able to. I got this error:

<img width="349" alt="Screenshot 2024-01-25 at 11 38 45 AM" src="https://github.com/Popcorn-Limited/vaultcraft/assets/155658337/26434db8-fa67-4ca8-a88d-8ba20e387dd8">

I tried chopping off decimals from the deposit amount to see if that would help but still received the error.

joey_pop

**Comment by alec-pop** [comment]
Closed with 10k oVCX reward

Issue is known and had been addressed on the UI
