### ISSUE TITLE
oVCX strike price issue

### ISSUE THREAD

**Issue by J-n-a-k** [Popcorn-Limited/vaultcraft#212]
The strike price for exercising oVCX has consistently represented less than a 25% discount on VCX. It's currently under 19%: 

<img width="735" alt="Screenshot 2024-01-31 at 12 52 03 PM" src="https://github.com/Popcorn-Limited/vaultcraft/assets/155658337/9d913349-7d00-404a-88b8-46c3cb4d8e0f">

I understand that this is a Balancer oracle issue that will be resolved when a certain threshold of transactions are made, but in the meantime it would be great to have a couple temporary solutions implemented:

1. A regular schedule for manual resets of the strike price (e.g. daily at certain time)
2. The actual, real-time discount displayed on the dApp (oVCX price ÷ VCX price) so that users can make an informed decision as to whether they want to exercise now or wait for the next reset.

joey_pop

**Comment by alec-pop** [comment]
Closing with 5000 oVCX reward

oVCX min price will be updated daily until Balancer oracle reaches minimum tx threshold

Keep in mind there may still be intraday fluctuations because oVCX is priced in WETH and the VCX/WETH ratio may be variable
