### ISSUE TITLE
WETH approval issue when exercising oVCX

### ISSUE THREAD

**Issue by J-n-a-k** [Popcorn-Limited/vaultcraft#215]
Exercising oVCX requires a WETH approval tx for every transaction, regardless of how much WETH was approved previously. 

You can approve WETH, and even without exercising any oVCX, need to approve it again if you happen to close the modal before executing the exercise tx. 

This has happened to me a least twice, so I don't believe it was a glitch. 

joey_pop

**Comment by J-n-a-k** [comment]
Just FYI I haven't tried it with infinite approval (I never use infinite approvals)

**Comment by alec-pop** [comment]
Looking into this now

**Comment by alec-pop** [comment]
Issue is fixed. Closing with 5k oVCX rewards
