### ISSUE TITLE
Display error? Boost % shown on dApp are inaccurate (low)

### ISSUE THREAD

**Issue by J-n-a-k** [Popcorn-Limited/vaultcraft#219]
Min / max boost percentages seem way too low to be accurate on all vaults with gauges:

<img width="1674" alt="Screenshot 2024-02-29 at 9 06 30 AM" src="https://github.com/Popcorn-Limited/vaultcraft/assets/155658337/ecda2366-7817-4857-8d12-7194c8ed2b96">

Consistent on the Boost page:

<img width="1644" alt="Screenshot 2024-02-29 at 9 12 28 AM" src="https://github.com/Popcorn-Limited/vaultcraft/assets/155658337/afc5dd15-1184-41b8-ac7c-acf210997fa6">

Seemed like something that might deter depositors so wanted to flag it. 

joey_pop

**Comment by alec-pop** [comment]
Thanks for pinging this! This was resolved immediately (issue with feeding the data as a percent vs decimal)

Closing ticket with 1000 oVCX reward
