### ISSUE TITLE
April'24 Release Checklist: Loan Modal 

### ISSUE THREAD

**Issue by Jogas28** [Popcorn-Limited/vaultcraft#232]
Description:

- Supplying into the loan modal functions properly, but the display of numbers seems incorrect (Screenshot 1). 
- Borrowing goes smoothly, but it's followed by a black screen, forcing a me to exit the loan modal(Screenshot 2). 
- Repaying loans consistently results in a black screen, with no further action possible  (Screenshot 3). 
- Withdrawing works correctly but the numerical formatting is off (Screenshot 4), and attempting to withdraw beyond the deposited amount triggers an error without specific details (Screenshot 5).

Environment:
URL: https://vaultcraft-git-feat-multichaingauges-0xpawp.vercel.app/vaults
Browser: Google Chrome Version 122.0.6261.129

Screenshot 1:
<img width="955" alt="Bildschirmfoto 2024-04-01 um 00 49 20" src="https://github.com/Popcorn-Limited/vaultcraft/assets/164196306/2c069d97-810e-414f-8519-24ea5891d6ce">

Screenshot 2: 
<img width="1425" alt="Bildschirmfoto 2024-04-01 um 00 57 10" src="https://github.com/Popcorn-Limited/vaultcraft/assets/164196306/9dcb9984-acbb-484f-8a07-d05ced73b93f">

Screenshot 3: 
[
<img width="1425" alt="Bildschirmfoto 2024-04-01 um 00 59 38" src="https://github.com/Popcorn-Limited/vaultcraft/assets/164196306/26108085-3c66-4b05-9fb8-841e4a0bf1a5">
](url)

Screenshot 4: 
<img width="928" alt="Bildschirmfoto 2024-04-01 um 01 01 40" src="https://github.com/Popcorn-Limited/vaultcraft/assets/164196306/71fe75a3-ff93-41ad-b510-8f541c3bfae7">

Screenshot 5: 
<img width="369" alt="Bildschirmfoto 2024-04-01 um 01 03 28" src="https://github.com/Popcorn-Limited/vaultcraft/assets/164196306/3bac075e-6515-4e26-9ee8-06be6c25b3b1">

**Comment by Mischa0x** [comment]
@RedVeil @Jogas28 hows it looking here?
