### ISSUE TITLE
April'24 Release Checklist: Broadcasting Vebalance

### ISSUE THREAD

**Issue by Jogas28** [Popcorn-Limited/vaultcraft#233]
Description:

When broadcasting veBalance to Arbitrum wallet authentication and signing work and confirmations appear (Screenshot 1), the interface still does not update the veBalance on Arbitrum, always showing 0 (Screenshot 2). (Also after reloading the page or connecting and disconnecting my wallet, veBalance remains at 0)

Environment:
URL: https://vaultcraft-git-feat-multichaingauges-0xpawp.vercel.app/vaults
Browser: Google Chrome Version 122.0.6261.129

Screenshot 1:
<img width="990" alt="Bildschirmfoto 2024-04-01 um 01 20 34" src="https://github.com/Popcorn-Limited/vaultcraft/assets/164196306/1998ee70-af71-490e-9c36-ff372ca36815">

Screenshot 2: 
<img width="955" alt="Bildschirmfoto 2024-04-01 um 01 24 59" src="https://github.com/Popcorn-Limited/vaultcraft/assets/164196306/7918d32c-469e-4d9d-8cd5-95a14435b6e1">

**Comment by Mischa0x** [comment]
@RedVeil can we change the copy to this:

**Sync veVCX**

Sync your veVCX to earn oVCX on Ethereum, Optimism, and Arbitrum.

IMPORTANT: If you don’t sync, you will not earn oVCX so please make sure you sync every time you lock, increase your lock amount, or increase your lock time.

**Comment by RedVeil** [comment]
@Mischa0x @Jogas28 Copy is updated to reflect that syncing takes soem time
