### ISSUE TITLE
Clarify oVCX Distribution Timing

### ISSUE THREAD

**Issue by Jogas28** [Popcorn-Limited/vaultcraft#253]
Tom pointed out that there is currently confusion among users regarding the timing of oVCX distributions. It should be clarified that oVCX rewards only accrue once a week, not daily. Weekly distributions occur after contract funding. Additionally it should be made clear that users still earn oVCX without the boost.

**Comment by enialoleon** [comment]
To address this issue, we can add a "more info" icon next to the "emissions per week" on Boostpage. When users hover over the icon, a tooltip will appear, providing the necessary explanation:

"oVCX rewards accrue weekly, not daily. Distributions happen post-contract funding. Note: You still earn oVCX even without the boost." 

Here design https://www.figma.com/design/kPTUKnb7DqgzoyyVemfSHW/POPCORN.-New-UI?node-id=1970-40567&t=V1rjjEBWoYNqXhqj-1
