### ISSUE TITLE
Suggestion to show total minimum APY and breakdown

### ISSUE THREAD

**Issue by Jogas28** [Popcorn-Limited/vaultcraft#254]
It would help to show the total minimum APY for each vault, along with a detailed breakdown of how this APY is achieved (e.g., base APY + boost APY). For instance, displaying 15% + 2% boost would provide users with a clearer understanding of their potential earnings and the components contributing to the total APY

**Comment by Jogas28** [comment]
Also it was pointed out that the displayed historical APY charts for multiple vaults, especially VCX LP, seem incorrect 
<img width="888" alt="Bildschirmfoto 2024-06-07 um 13 03 02" src="https://github.com/Popcorn-Limited/vaultcraft/assets/164196306/e54195bc-b79f-4415-9c98-844197c690e2">

**Comment by RedVeil** [comment]
Im gonna cut out the first few extreme days of the chart. Added it now. Rest is already implemented
