### ISSUE TITLE
Display Underlying Protocol TVL

### ISSUE THREAD

**Issue by Jogas28** [Popcorn-Limited/vaultcraft#255]
To increase investor confidence, Tom suggested to display the TVL of the underlying protocols associated with each vault. This would boost investor confidence in sales calles

**Comment by enialoleon** [comment]
To address this suggestion, we can add a tooltip that displays the TVL when users hover over the protocol icon. Given the limited space on the input row and the secondary nature of this information, a tooltip provides an effective solution.

**Comment by RedVeil** [comment]
This was added in the v2 ui when you hover over the TVL in a row. it appears in the tooltip
